### ISSUE TITLE
Number of 'Log in' choices inconsistent

### ISSUE THREAD

**Issue by laureenas** [ManoSeimas/manoseimas.lt#37] opened 2015-09-17 13:54 UTC
The number of Log in choices is inconsistent on different pages and on different form factors:

![image](https://cloud.githubusercontent.com/assets/4104268/9934663/69369a08-5d5b-11e5-8f5a-97370b65c271.png)

![image](https://cloud.githubusercontent.com/assets/4104268/9934707/a4365b66-5d5b-11e5-95df-c7cbc99b92e2.png)

![image](https://cloud.githubusercontent.com/assets/4104268/9935107/8246197c-5d5d-11e5-97f7-30e0716a4705.png)

Chromium Version 44.0.2403.89 Ubuntu 14.04 (64-bit)

Related to story: #41

**Comment by mgedmin** [comment] 2015-09-25 10:46
Duplicate of #36.

**Closed by mgedmin** 2015-09-25 10:46 UTC
Labels: bug, priority: 3 - low
